#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TuristickaAgencija.MobileApp.Droid.Resource", IsApplication=true)]

namespace TuristickaAgencija.MobileApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.font = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.actions = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.async = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::TuristickaAgencija.MobileApp.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::TuristickaAgencija.MobileApp.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::TuristickaAgencija.MobileApp.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromLeft = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromRight = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToLeft = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToRight = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.collectionViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.font = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.font;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.scrollViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Boolean.abc_action_bar_embed_tabs = global::TuristickaAgencija.MobileApp.Droid.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_action_color_filter = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_icon_bg_color = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Forms.Platform.Android.Resource.Color.ripple_material_light = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.ripple_material_light;
			global::Xamarin.Forms.Platform.Android.Resource.Color.secondary_text_default_material_light = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_inset_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_inset_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_padding_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_padding_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_control_corner_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_action_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_action_text_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_big_circle_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_content_margin_start = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_large_icon_height = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_large_icon_width = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_main_column_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_media_narrow_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_right_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_right_side_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_small_icon_background_padding = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_small_icon_size_as_large = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_subtext_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_top_pad = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_top_pad_large_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_action_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_normal_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_icon_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_template_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_template_icon_low_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_tile_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notify_panel_notification_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Id.actions = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.actions;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_container;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_divider = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_image = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_image;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_text;
			global::Xamarin.Forms.Platform.Android.Resource.Id.async = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.async;
			global::Xamarin.Forms.Platform.Android.Resource.Id.blocking = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.blocking;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_navarea = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_tabbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.forever = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.forever;
			global::Xamarin.Forms.Platform.Android.Resource.Id.icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Android.Resource.Id.icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon_group;
			global::Xamarin.Forms.Platform.Android.Resource.Id.info = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.info;
			global::Xamarin.Forms.Platform.Android.Resource.Id.italic = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.italic;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line1 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line3 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_tablayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_viewpager = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Android.Resource.Id.normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.normal;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_background;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right_icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_icon;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right_side = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.sliding_tabs = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Id.tag_transition_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Android.Resource.Id.time = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.time;
			global::Xamarin.Forms.Platform.Android.Resource.Id.title = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.title;
			global::Xamarin.Forms.Platform.Android.Resource.Id.toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Integer.status_bar_notification_info_maxnum = global::TuristickaAgencija.MobileApp.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.BottomTabLayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackTabbarDoNotUse = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackToolbarDoNotUse = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FlyoutContent = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_action = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_action_tombstone = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_custom_big = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_part_chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_part_time = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.RootLayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.ShellContent = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Tabbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.String.overflow_tab_title = global::TuristickaAgencija.MobileApp.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Android.Resource.String.status_bar_notification_info_overflow = global::TuristickaAgencija.MobileApp.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Forms.Platform.Android.Resource.Style.AppCompatDialogStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Style.collectionViewTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme_Base = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewScrollBars = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Info = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Time = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Title = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_Compat_NotificationActionContainer = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_Compat_NotificationActionText = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromLeft = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromRight = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToLeft = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToRight = global::TuristickaAgencija.MobileApp.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Resource.Attribute.collectionViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Attribute.font = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.font;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Forms.Platform.Resource.Attribute.fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Forms.Platform.Resource.Attribute.scrollViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Boolean.abc_action_bar_embed_tabs = global::TuristickaAgencija.MobileApp.Droid.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Forms.Platform.Resource.Color.notification_action_color_filter = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Forms.Platform.Resource.Color.notification_icon_bg_color = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Forms.Platform.Resource.Color.ripple_material_light = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.ripple_material_light;
			global::Xamarin.Forms.Platform.Resource.Color.secondary_text_default_material_light = global::TuristickaAgencija.MobileApp.Droid.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Forms.Platform.Resource.Dimension.compat_button_inset_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Forms.Platform.Resource.Dimension.compat_button_inset_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Forms.Platform.Resource.Dimension.compat_button_padding_horizontal_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Forms.Platform.Resource.Dimension.compat_button_padding_vertical_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Forms.Platform.Resource.Dimension.compat_control_corner_material = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_action_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_action_text_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_big_circle_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_content_margin_start = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_large_icon_height = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_large_icon_width = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_main_column_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_media_narrow_margin = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_right_icon_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_right_side_padding_top = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_small_icon_background_padding = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_small_icon_size_as_large = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_subtext_size = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_top_pad = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_top_pad_large_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_action_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg_low = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg_low_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg_low_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg_normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_bg_normal_pressed = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_icon_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_template_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_template_icon_low_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_tile_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Forms.Platform.Resource.Drawable.notify_panel_notification_icon_bg = global::TuristickaAgencija.MobileApp.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Forms.Platform.Resource.Id.actions = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.actions;
			global::Xamarin.Forms.Platform.Resource.Id.action_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_container;
			global::Xamarin.Forms.Platform.Resource.Id.action_divider = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Resource.Id.action_image = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_image;
			global::Xamarin.Forms.Platform.Resource.Id.action_text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.action_text;
			global::Xamarin.Forms.Platform.Resource.Id.async = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.async;
			global::Xamarin.Forms.Platform.Resource.Id.blocking = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.blocking;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_navarea = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_tabbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Resource.Id.chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Resource.Id.flyoutcontent_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.forever = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.forever;
			global::Xamarin.Forms.Platform.Resource.Id.icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Resource.Id.icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.icon_group;
			global::Xamarin.Forms.Platform.Resource.Id.info = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.info;
			global::Xamarin.Forms.Platform.Resource.Id.italic = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.italic;
			global::Xamarin.Forms.Platform.Resource.Id.line1 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Resource.Id.line3 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Resource.Id.main_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_tablayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Resource.Id.main_toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_viewpager = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Resource.Id.normal = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.normal;
			global::Xamarin.Forms.Platform.Resource.Id.notification_background = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_background;
			global::Xamarin.Forms.Platform.Resource.Id.notification_main_column = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Platform.Resource.Id.notification_main_column_container = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Platform.Resource.Id.right_icon = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_icon;
			global::Xamarin.Forms.Platform.Resource.Id.right_side = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_appbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.sliding_tabs = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Resource.Id.tag_transition_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Forms.Platform.Resource.Id.text = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text;
			global::Xamarin.Forms.Platform.Resource.Id.text2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Resource.Id.time = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.time;
			global::Xamarin.Forms.Platform.Resource.Id.title = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.title;
			global::Xamarin.Forms.Platform.Resource.Id.toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Resource.Integer.status_bar_notification_info_maxnum = global::TuristickaAgencija.MobileApp.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Forms.Platform.Resource.Layout.BottomTabLayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackTabbarDoNotUse = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackToolbarDoNotUse = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FlyoutContent = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_action = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_action_tombstone = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_custom_big = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_icon_group = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_part_chronometer = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_part_time = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Forms.Platform.Resource.Layout.RootLayout = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.ShellContent = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Resource.Layout.Tabbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Resource.Layout.Toolbar = global::TuristickaAgencija.MobileApp.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Resource.String.overflow_tab_title = global::TuristickaAgencija.MobileApp.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Resource.String.status_bar_notification_info_overflow = global::TuristickaAgencija.MobileApp.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Forms.Platform.Resource.Style.AppCompatDialogStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Resource.Style.collectionViewTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme_Base = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewScrollBars = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Info = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Time = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Title = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Forms.Platform.Resource.Style.Widget_Compat_NotificationActionContainer = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Forms.Platform.Resource.Style.Widget_Compat_NotificationActionText = global::TuristickaAgencija.MobileApp.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_android_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_font = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_fontStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamilyFont_fontWeight = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderAuthority = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderCerts = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderPackage = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Forms.Platform.Resource.Styleable.FontFamily_fontProviderQuery = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::TuristickaAgencija.MobileApp.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int EnterFromLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int EnterFromRight = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ExitToLeft = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExitToRight = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int collectionViewStyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int font = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fontProviderAuthority = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fontProviderCerts = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fontProviderFetchStrategy = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fontProviderFetchTimeout = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderPackage = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderQuery = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontStyle = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontWeight = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int scrollViewStyle = 2130837514;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F030000
			public const int abc_action_bar_embed_tabs = 2130903040;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int colorAccent = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int colorPrimary = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int colorPrimaryDark = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int launcher_background = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_action_color_filter = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_icon_bg_color = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ripple_material_light = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int secondary_text_default_material_light = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int compat_button_inset_horizontal_material = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int compat_button_inset_vertical_material = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int compat_button_padding_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int compat_button_padding_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int compat_control_corner_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_action_icon_size = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_action_text_size = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_big_circle_margin = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_content_margin_start = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_large_icon_height = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_large_icon_width = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_main_column_padding_top = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_media_narrow_margin = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_right_icon_size = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_right_side_padding_top = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_small_icon_background_padding = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_small_icon_size_as_large = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_subtext_size = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_top_pad = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_top_pad_large_text = 2131034131;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int icon_about = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int icon_feed = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int notification_action_background = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int notification_bg = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int notification_bg_low = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int notification_bg_low_normal = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int notification_bg_low_pressed = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int notification_bg_normal = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int notification_bg_normal_pressed = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int notification_icon_background = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int notification_template_icon_bg = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int notification_template_icon_low_bg = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int notification_tile_bg = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notify_panel_notification_icon_bg = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int xamarin_logo = 2131099662;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070004
			public const int actions = 2131165188;
			
			// aapt resource value: 0x7F070000
			public const int action_container = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int action_divider = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int action_image = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int action_text = 2131165187;
			
			// aapt resource value: 0x7F070005
			public const int async = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int blocking = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int bottomtab_navarea = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int bottomtab_tabbar = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int chronometer = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int flyoutcontent_appbar = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int forever = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int icon = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int icon_group = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int info = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int italic = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int line1 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int line3 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int main_appbar = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int main_tablayout = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int main_toolbar = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int main_viewpager = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int mask = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int normal = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int notification_background = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int notification_main_column = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int notification_main_column_container = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int right_icon = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int right_side = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int shellcontent_appbar = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int shellcontent_toolbar = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int sliding_tabs = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int tag_transition_group = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int text = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int text2 = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int time = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int title = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int toolbar = 2131165221;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int status_bar_notification_info_maxnum = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public const int BottomTabLayout = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int FallbackTabbarDoNotUse = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int FallbackToolbarDoNotUse = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int FlyoutContent = 2131296259;
			
			// aapt resource value: 0x7F090008
			public const int notification_action = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int notification_action_tombstone = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int notification_template_custom_big = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int notification_template_icon_group = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int notification_template_part_chronometer = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int notification_template_part_time = 2131296269;
			
			// aapt resource value: 0x7F090004
			public const int RootLayout = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int ShellContent = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Tabbar = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Toolbar = 2131296263;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0A0000
			public const int icon = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int icon_round = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int launcher_foreground = 2131361794;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int overflow_tab_title = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int status_bar_notification_info_overflow = 2131427329;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppCompatDialogStyle = 2131492864;
			
			// aapt resource value: 0x7F0C000A
			public const int collectionViewTheme = 2131492874;
			
			// aapt resource value: 0x7F0C0001
			public const int MainTheme = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int MainTheme_Base = 2131492866;
			
			// aapt resource value: 0x7F0C000B
			public const int scrollViewScrollBars = 2131492875;
			
			// aapt resource value: 0x7F0C000C
			public const int scrollViewTheme = 2131492876;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Info = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification_Line2 = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int TextAppearance_Compat_Notification_Time = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int TextAppearance_Compat_Notification_Title = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int Widget_Compat_NotificationActionContainer = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int Widget_Compat_NotificationActionText = 2131492873;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007 }
			public static int[] FontFamily = new int[] {
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x7F020001,0x7F020008,0x7F020009 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130837505,
					2130837512,
					2130837513};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x7F020000 }
			public static int[] ItemsViewRendererTheme = new int[] {
					2130837504};
			
			// aapt resource value: 0
			public const int ItemsViewRendererTheme_collectionViewStyle = 0;
			
			// aapt resource value: { 0x7F02000A }
			public static int[] ScrollViewRendererTheme = new int[] {
					2130837514};
			
			// aapt resource value: 0
			public const int ScrollViewRendererTheme_scrollViewStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0E0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131623936;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
